### ISSUE TITLE
Why to use Babel if Typescript can compile to arbitrary target?

### ISSUE THREAD

**Issue by ichyr** [vikpe/react-webpack-typescript-starter#10]

**Comment by vikpe** [comment]
@ichyr I guess you can skip Babel if all you want to do is compile a production build.

This setup is using React Hot Loader (a Babel plugin) in order to support hot module reloading (HMR) which in my opinion is a must have during development.

**Comment by ichyr** [comment]
Can't we use webpack for that?

**Comment by vikpe** [comment]
Feel free to create a pull request if you can get HMR to work with React smoothly without babel/react-hot-loader. I remember having some troubles a year ago when I tried.

The [official webpack docs](https://webpack.js.org/guides/hot-module-replacement/#other-code-and-frameworks) refer to React Hot Loader.
