### ISSUE TITLE
Don't use minified build of React in development

### ISSUE THREAD

**Issue by remi2j** [vikpe/react-webpack-typescript-starter#14]
**Enhancement request**

Using the minified build of React makes it annoying to debug a React error.

As a result, error messages in the console look like this: `react-dom.production.min.js:110 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. `

When they should look like this: `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`

**Comment by vikpe** [comment]
@remi2j thanks for the notice, I'll look into it.

**Comment by remi2j** [comment]
Nice. On my end I currently have 2 files to fix this: `template.dev.html.ejs` and `template.prod.html.ejs`, each loading a different version of React.

I wish I could still have only one file though. There's probably a way but I haven't looked much into it. Let me know if you find a solution 👍

**Comment by vikpe** [comment]
@remi2j fixed in https://github.com/vikpe/react-webpack-typescript-starter/commit/cf186f0561bbd881405e5257d27573618c4e19d3

https://github.com/vikpe/react-webpack-typescript-starter/blob/cf186f0561bbd881405e5257d27573618c4e19d3/src/index.html.ejs#L11-L18

If you find a better solution, please submit a PR.

**Comment by remi2j** [comment]
That's perfect, thanks!
