### ISSUE TITLE
[ Question] Change default Port

### ISSUE THREAD

**Issue by mboullouz** [vikpe/react-webpack-typescript-starter#17]
How to change the default port from 8080 to something else?

**Comment by vikpe** [comment]
@ismail-codar the port for the development server is changed in the webpack config, under [`devServer.port`](https://webpack.js.org/configuration/dev-server/#devserver-port).

**Example**: change port to `3000`.

https://github.com/vikpe/react-webpack-typescript-starter/blob/bde949ada07a38b303f46b1735b515bb3d4fb67b/configs/webpack/dev.js#L8-L16

change to:
```
  entry: [
    'react-hot-loader/patch', // activate HMR for React
    'webpack-dev-server/client?http://localhost:3000',// bundle the client for webpack-dev-server and connect to the provided endpoint
    'webpack/hot/only-dev-server', // bundle the client for hot reloading, only- means to only hot reload for successful updates
    './index.tsx' // the entry point of our app
  ],
  devServer: {
    hot: true, // enable HMR on the server
    port: 3000
  },
```
