### ISSUE TITLE
tslint -p .     ?

### ISSUE THREAD

**Issue by xahon** [vikpe/react-webpack-typescript-starter#28]
https://github.com/vikpe/react-webpack-typescript-starter/blob/82e24bb61d3f021ab0f5fe6600ce165495ac41ac/package.json#L28

**Comment by vikpe** [comment]
> By default, TSLint looks for a configuration file named tslint.json in the directory of the file being linted and, if not found, searches ancestor directories.

However, `-p .` might speed up the script as it will skip the search. Will fix asap!

**Comment by vikpe** [comment]
Fixed.
