### ISSUE TITLE
jest --watch disable the coverage report

### ISSUE THREAD

**Issue by asimashfaq** [vikpe/react-webpack-typescript-starter#32]
``jest --watch disable the coverage report``
Do we need to disable watch mode to generate the coverage?

**Comment by vikpe** [comment]
I'm not sure what you are asking for.

The `test` script in `package.json` is defined as:
```sh
jest --watch --coverage --config=configs/jest.json
```

* If you want to disable coverage, remove `--coverage`
* If you want to disable watch (run test on file changes), remove `--watch`

See [jest cli options docs](https://jestjs.io/docs/en/cli) for more info.

**Comment by vikpe** [comment]
@asimashfaq It seems like there is an issue with `--coverage` in combination with `--watch` [(see issue).](https://github.com/facebook/jest/issues/7331)

I've updated the `test` script to use `--watchAll` instead of `--watch`. 

I've tested at it works fine for me, can you give it a try?

**Comment by asimashfaq** [comment]
Worked.

**Comment by vikpe** [comment]
Nice! Thank you for reporting this issue.
