### ISSUE TITLE
TSLint has been deprecated

### ISSUE THREAD

**Issue by cseas** [vikpe/react-webpack-typescript-starter#36]
The npm package `tslint` has been deprecated in favour of `eslint`.
Reference: https://www.npmjs.com/package/tslint

Should the tslint package be replaced with `typescript-eslint` in this project?

**Comment by vikpe** [comment]
Probably yes, I'll look into it. Thanks for the notice!

**Comment by vikpe** [comment]
I replaced tslint with [eslint](https://github.com/eslint/eslint)+[prettier](https://github.com/prettier/prettier), see https://github.com/vikpe/react-webpack-typescript-starter/commit/260c2e1752a5761aa8dad5e9f07fd69e94391c70.

**Comment by cseas** [comment]
That's awesome, thanks! :tada:
