### ISSUE TITLE
Why are react and react-dom not npm dependencies?

### ISSUE THREAD

**Issue by justin-hackin** [vikpe/react-webpack-typescript-starter#48]
The design choice to make React libs provided by script tags seems counter-intuitive. Installing libraries with react as a peer dependency will never have their peer dependencies met and npm will not know if the library is compatible with the script version of React. Is there some rationale behind this choice that I'm not aware of?

**Comment by vikpe** [comment]
It reduces build time during development and load time for users as there is a high chance that they already have React/ReactDOM in their browser cache.
