### ISSUE TITLE
React-Router error

### ISSUE THREAD

**Issue by naftalimurgor** [vikpe/react-webpack-typescript-starter#52]
Hello @vikpe 
I am using this starter for a project that using the React Router library for routing. However, I  keep getting an  error `cannot GET /my-account` .  I did a little searching and saw a similar question here: https://stackoverflow.com/questions/43209666/react-router-v4-cannot-get-url  with further explanation here: https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually and it is indeed a small problem with  webpack configuration and the History API. Can I submit a PR that fixes this issue?
 Thank you

**Comment by vikpe** [comment]
@naftalimurgor please do. sorry for such a late response.

**Comment by naftalimurgor** [comment]
@vikpe  It's ok, totally understandable.
