### ISSUE TITLE
Needs active internet connection to run the app

### ISSUE THREAD

**Issue by Tasin5541** [vikpe/react-webpack-typescript-starter#53]
`    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/react/17.0.1/umd/react.production.min.js"
      integrity="sha512-YMtLFKDKe5a4zi7rJ0y4wdGErKZe3tx7L+AXDTxjNDzkv7jsaNhvumeU1xQvw6UqVwBVmYlO9NhsSuSVPUN/xQ=="
      crossorigin="anonymous"
    ></script>`

How can I localize this script so the app runs offline?

**Comment by vikpe** [comment]
@Tasin5541 

**Step 1**: remove the `externals` section from [configs/webpack/common.js](https://github.com/vikpe/react-webpack-typescript-starter/blob/39309a9fbb93ccc978d981c88392e59d4f9ef756/configs/webpack/common.js)
https://github.com/vikpe/react-webpack-typescript-starter/blob/39309a9fbb93ccc978d981c88392e59d4f9ef756/configs/webpack/common.js#L35-L38

**Step 2**: remove the externally linked dependencies from [src/index.html.ejs](https://github.com/vikpe/react-webpack-typescript-starter/blob/39309a9fbb93ccc978d981c88392e59d4f9ef756/src/index.html.ejs)
https://github.com/vikpe/react-webpack-typescript-starter/blob/39309a9fbb93ccc978d981c88392e59d4f9ef756/src/index.html.ejs#L11-L18

**Comment by Tasin5541** [comment]
> @Tasin5541
> 
> **Step 1**: remove the `externals` section from [configs/webpack/common.js](https://github.com/vikpe/react-webpack-typescript-starter/blob/39309a9fbb93ccc978d981c88392e59d4f9ef756/configs/webpack/common.js)
> https://github.com/vikpe/react-webpack-typescript-starter/blob/39309a9fbb93ccc978d981c88392e59d4f9ef756/configs/webpack/common.js#L35-L38
> 
> **Step 2**: remove the externally linked dependencies from [src/index.html.ejs](https://github.com/vikpe/react-webpack-typescript-starter/blob/39309a9fbb93ccc978d981c88392e59d4f9ef756/src/index.html.ejs)
> https://github.com/vikpe/react-webpack-typescript-starter/blob/39309a9fbb93ccc978d981c88392e59d4f9ef756/src/index.html.ejs#L11-L18

Can you tell me what's the use of these cdn links? Aren't we already including react and react dom in the package?

**Comment by vikpe** [comment]
Its a performance optimization. They are not bundled into the build, instead they are linked externally.

> Prevent bundling of certain imported packages and instead retrieve these external dependencies at runtime.

https://webpack.js.org/configuration/externals/

**Comment by Tasin5541** [comment]
Will it work the same if I download the js files and load it locally in the script?

**Comment by vikpe** [comment]
You can download react/react-dom and change the `src` tags to the local versions.

**Comment by Tasin5541** [comment]
> You can download react/react-dom and change the `src` tags to the local versions.

Thanks a bunch
