### ISSUE TITLE
node-sass error on windows

### ISSUE THREAD

**Issue by josejaviersanahuja** [vikpe/react-webpack-typescript-starter#57]
ERROR in ./assets/scss/App.scss (../node_modules/css-loader/dist/cjs.js!../node_modules/sass-loader/dist/cjs.js!./assets/scss/App.scss)
Module Error (from ../node_modules/sass-loader/dist/cjs.js):
Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v5.0.0

Hi, it is probably my versions of node, or windows that node-sass is not supported.

Anyway, i learnt a lot with your project. a star for you

**Comment by vikpe** [comment]
@josejaviersanahuja the supported node versions for node-sass on windows are: 10, 12, 14, 15

Run `node --version` to see what version you have installed.

**Comment by josejaviersanahuja** [comment]
Yes, that's why i put it above. i am currently on Node 16. if try it again i will let you know.

**Comment by vikpe** [comment]
I updated the dependencies, among is node-sass (from 5.x to 6.x) which supports node v16.
