### ISSUE TITLE
issue when running app using yarn start-dev

### ISSUE THREAD

**Issue by chapster11** [vikpe/react-webpack-typescript-starter#58]
ERROR in ./index.tsx
Module build failed (from ../node_modules/babel-loader/lib/index.js):
SyntaxError: /temp/src/index.tsx: Support for the experimental syntax 'jsx' isn't currently enabled (7:8):

  5 | const rootEl = document.getElementById("root");
  6 |
> 7 | render(<App />, rootEl);

**Comment by chapster11** [comment]
Had to add .babelrc file 
{
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}

Probably should add that by default to the repo.

**Comment by vikpe** [comment]
@chapster11 There is a [.babelrc](https://github.com/vikpe/react-webpack-typescript-starter/blob/master/.babelrc) present in the repo root.
