### ISSUE TITLE
React taken from cdn and is in webpack externals

### ISSUE THREAD

**Issue by iBobb** [vikpe/react-webpack-typescript-starter#62]
Hi there, the idea of webpack externals is a bit new to me, I saw their documentation, one of the things they mentioned it could be useful for library developers. What is the benefit of having it in this template and loading react from a CDN instead of packaging it with the bundle as usual, taken from npm?

**Comment by vikpe** [comment]
It reduces build time during development and load time for users as there is a high chance that they already have React/ReactDOM in their browser cache.

**Comment by iBobb** [comment]
I see, I got to think about this when I got crossorigin request issues and since the app that I'm building currently might be hosted on a machine that doesn't even have full internet access, I decided to stick to packaging the bundle with the app locally. Thanks for the info though. As for the crossorigin issue, I saw a suggestion to add "crossorigin" to the script tag in the ejs file, haven't tested if that worked.
