### ISSUE TITLE
Reload on nested path gives error

### ISSUE THREAD

**Issue by Tasin5541** [vikpe/react-webpack-typescript-starter#71]
Let's say your current path: `page1/page1.2`
You hit reload
You see an error that /page1/index.js is not found.

Now let's say your current path: `page1/page1.2/page1.2.3`
You hit reload
You see an error that /page1/page1.2/index.js is not found

Why is it searching for index.js in the parent path instead of the root path?

**Comment by vikpe** [comment]
@Tasin5541 the default behaviour for web servers is to look for an index file in the given dir path.

Depending on your choice of web server you need to configure it to rewrite unknown paths to your root index page, e.g. https://tecadmin.net/solving-react-404-error/

**Comment by Tasin5541** [comment]
> @Tasin5541 the default behaviour for web servers is to look for an index file in the given dir path.
> 
> Depending on your choice of web server you need to configure it to rewrite unknown paths to your root index page, e.g. https://tecadmin.net/solving-react-404-error/

I'm talking about the dev server

**Comment by vikpe** [comment]
You can set `historyApiFallback` in `configs/webpack/dev.js` to an object containing `rewrites`.

```js
{
  historyApiFallback: {
      rewrites: [
        {
          from: /^.+main\.js$/,
          to: "/main.js",
        },
        {
          from: /^.*$/,
          to: "/",
        },
      ],
    },
  }
```

**Comment by Tasin5541** [comment]
> You can set `historyApiFallback` in `configs/webpack/dev.js` to an object containing `rewrites`. [(see docs)](https://webpack.js.org/configuration/dev-server/#devserverhistoryapifallback)
> 
> ```js
> {
>   historyApiFallback: {
>       rewrites: [
>         {
>           from: /^.+main\.js$/,
>           to: "/main.js",
>         },
>         {
>           from: /^.*$/,
>           to: "/",
>         },
>       ],
>     },
>   }
> ```

Great! Thanks for the help
